export const yearLevels = ["Freshman", "Sophomore", "Junior", "Senior"];

export const majors = [
  "Economics",
  "Business",
  "Computer Science",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Biomedical Engineering",
  "Computer Engineering",
  "Information Science",
  "Data Science",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Psychology",
  "Sociology",
  "Political Science",
  "History",
  "English",
  "Philosophy",
  "Art",
  "Architecture",
  "Design",
  "Communications",
  "Journalism",
  "Marketing",
  "Finance",
  "Accounting",
  "Management",
  "Human Resources",
  "International Relations",
  "Environmental Science",
  "Agriculture",
  "Food Science",
  "Nutrition",
  "Public Health",
  "Nursing",
  "Pre-Medicine",
  "Pre-Law",
  "Education",
  "Linguistics",
  "Anthropology",
  "Geography",
  "Geology",
  "Astronomy",
  "Statistics",
  "Actuarial Science",
  "Hospitality Management",
  "Tourism",
  "Sports Management",
  "Music",
  "Theater",
  "Film Studies",
  "Media Studies",
  "Digital Arts",
  "Graphic Design",
  "Industrial Design",
  "Urban Planning",
  "Landscape Architecture",
  "Interior Design",
  "Fashion Design",
  "Textile Design",
  "Industrial Engineering",
  "Systems Engineering",
  "Aerospace Engineering",
  "Nuclear Engineering",
  "Materials Science",
  "Nanotechnology",
  "Robotics",
  "Artificial Intelligence",
  "Cybersecurity",
  "Software Engineering",
  "Game Design",
  "Web Development",
  "Mobile App Development",
  "Database Administration",
  "Network Administration",
  "Cloud Computing",
  "Machine Learning",
  "Data Analytics",
  "Business Analytics",
  "Supply Chain Management",
  "Operations Management",
  "Project Management",
  "Entrepreneurship",
  "Innovation Management",
  "Sustainability",
  "Renewable Energy",
  "Climate Science",
  "Oceanography",
  "Meteorology",
  "Atmospheric Science",
  "Marine Biology",
  "Wildlife Biology",
  "Conservation Biology",
  "Ecology",
  "Evolutionary Biology",
  "Genetics",
  "Microbiology",
  "Immunology",
  "Neuroscience",
  "Cognitive Science",
  "Behavioral Science",
  "Social Work",
  "Criminal Justice",
  "Criminology",
  "Forensic Science",
  "Law Enforcement",
  "Public Administration",
  "Public Policy",
  "Urban Studies",
  "Rural Development",
  "International Business",
  "Global Studies",
  "Area Studies",
  "Cultural Studies",
  "Gender Studies",
  "Women's Studies",
  "African American Studies",
  "Asian American Studies",
  "Latino Studies",
  "Native American Studies",
  "Middle Eastern Studies",
  "European Studies",
  "Latin American Studies",
  "African Studies",
  "Asian Studies",
  "Religious Studies",
  "Theology",
  "Biblical Studies",
  "Islamic Studies",
  "Jewish Studies",
  "Buddhist Studies",
  "Hindu Studies",
  "Comparative Religion",
  "Ethics",
  "Logic",
  "Metaphysics",
  "Epistemology",
  "Aesthetics",
  "Political Philosophy",
  "Moral Philosophy",
  "Applied Ethics",
  "Bioethics",
  "Environmental Ethics",
  "Business Ethics",
  "Medical Ethics",
  "Legal Ethics",
  "Journalism Ethics",
  "Media Ethics",
  "Digital Ethics",
  "Technology Ethics",
  "AI Ethics",
  "Data Ethics",
  "Privacy Studies",
  "Security Studies",
  "Intelligence Studies",
  "Strategic Studies",
  "Military Science",
  "Defense Studies",
  "Peace Studies",
  "Conflict Resolution",
  "Mediation",
  "Arbitration",
  "Negotiation",
  "Diplomacy",
  "International Law",
  "Human Rights",
  "Humanitarian Studies",
  "Development Studies",
  "Aid Studies",
  "Nonprofit Management",
  "Philanthropy",
  "Volunteer Management",
  "Community Development",
  "Rural Development",
  "Urban Development",
  "Regional Planning",
  "Transportation Planning",
  "Housing Studies",
  "Real Estate",
  "Property Management",
  "Construction Management",
  "Project Management",
  "Risk Management",
  "Quality Management",
  "Change Management",
  "Knowledge Management",
  "Information Management",
  "Records Management",
  "Archival Studies",
  "Library Science",
  "Information Architecture",
  "User Experience Design",
  "Human-Computer Interaction",
  "Usability Studies",
  "Accessibility Studies",
  "Inclusive Design",
  "Universal Design",
  "Design Thinking",
  "Creative Problem Solving",
  "Innovation Design",
  "Service Design",
  "Product Design",
  "Industrial Design",
  "Furniture Design",
  "Lighting Design",
  "Sound Design",
  "Visual Effects",
  "Animation",
  "Motion Graphics",
  "Video Production",
  "Audio Production",
  "Podcasting",
  "Broadcasting",
  "Streaming Media",
  "Digital Media",
  "Interactive Media",
  "Virtual Reality",
  "Augmented Reality",
  "Mixed Reality",
  "Extended Reality",
  "Immersive Media",
  "360° Video",
  "Spatial Computing",
  "Haptic Technology",
  "Gesture Recognition",
  "Voice Recognition",
  "Natural Language Processing",
  "Computational Linguistics",
  "Speech Recognition",
  "Text-to-Speech",
  "Speech-to-Text",
  "Translation Studies",
  "Interpretation",
  "Localization",
  "Globalization",
  "Cross-Cultural Communication",
  "Intercultural Studies",
  "Multicultural Studies",
  "Diversity Studies",
  "Inclusion Studies",
  "Equity Studies",
  "Social Justice",
  "Racial Justice",
  "Gender Justice",
  "Economic Justice",
  "Environmental Justice",
  "Climate Justice",
  "Food Justice",
  "Housing Justice",
  "Health Justice",
  "Educational Justice",
  "Criminal Justice Reform",
  "Prison Reform",
  "Police Reform",
  "Legal Reform",
  "Constitutional Law",
  "Criminal Law",
  "Civil Law",
  "Corporate Law",
  "Tax Law",
  "Environmental Law",
  "Health Law",
  "Education Law",
  "Employment Law",
  "Labor Law",
  "Immigration Law",
  "Family Law",
  "Property Law",
  "Contract Law",
  "Tort Law",
  "Administrative Law",
  "Regulatory Law",
  "Compliance",
  "Governance",
  "Corporate Governance",
  "Public Governance",
  "Digital Governance",
  "Data Governance",
  "Information Governance",
  "Knowledge Governance",
  "Innovation Governance",
  "Technology Governance",
  "AI Governance",
  "Algorithmic Governance",
  "Platform Governance",
  "Network Governance",
  "Collaborative Governance",
  "Participatory Governance",
  "Deliberative Democracy",
  "Direct Democracy",
  "Representative Democracy",
  "Constitutional Democracy",
  "Liberal Democracy",
  "Social Democracy",
  "Democratic Socialism",
  "Socialism",
  "Communism",
  "Capitalism",
  "Free Market",
  "Mixed Economy",
  "Planned Economy",
  "Command Economy",
  "Market Economy",
  "Gig Economy",
  "Sharing Economy",
  "Circular Economy",
  "Green Economy",
  "Blue Economy",
  "Digital Economy",
  "Knowledge Economy",
  "Creative Economy",
  "Experience Economy",
  "Attention Economy",
  "Data Economy",
  "Platform Economy",
  "Network Economy",
  "Peer Economy",
  "Collaborative Economy",
  "Solidarity Economy",
  "Social Economy",
  "Community Economy",
  "Local Economy",
  "Regional Economy",
  "National Economy",
  "Global Economy",
  "World Economy",
  "International Economy",
  "Transnational Economy",
  "Multinational Economy",
  "Supranational Economy",
  "Intergovernmental Economy",
  "Non-governmental Economy",
  "Civil Society",
  "Third Sector",
  "Voluntary Sector",
  "Charitable Sector",
  "Philanthropic Sector",
  "Social Sector",
  "Public Sector",
  "Private Sector",
  "Corporate Sector",
  "Business Sector",
  "Commercial Sector",
  "Industrial Sector",
  "Manufacturing Sector",
  "Service Sector",
  "Financial Sector",
  "Banking Sector",
  "Insurance Sector",
  "Real Estate Sector",
  "Construction Sector",
  "Transportation Sector",
  "Logistics Sector",
  "Supply Chain Sector",
  "Retail Sector",
  "Wholesale Sector",
  "Trade Sector",
  "Commerce Sector",
  "E-commerce Sector",
  "Digital Commerce",
  "Online Commerce",
  "Mobile Commerce",
  "Social Commerce",
  "Peer-to-Peer Commerce",
  "Marketplace Commerce",
  "Platform Commerce",
  "API Economy",
  "Microservices",
  "Serverless Computing",
  "Edge Computing",
  "Fog Computing",
  "Distributed Computing",
  "Parallel Computing",
  "Quantum Computing",
  "Neuromorphic Computing",
  "Biocomputing",
  "DNA Computing",
  "Molecular Computing",
  "Chemical Computing",
  "Optical Computing",
  "Photonics",
  "Electronics",
  "Microelectronics",
  "Nanoelectronics",
  "Spintronics",
  "Valleytronics",
  "Topological Insulators",
  "Quantum Materials",
  "2D Materials",
  "Graphene",
  "Carbon Nanotubes",
  "Quantum Dots",
  "Metamaterials",
  "Smart Materials",
  "Responsive Materials",
  "Adaptive Materials",
  "Self-healing Materials",
  "Biodegradable Materials",
  "Sustainable Materials",
  "Green Materials",
  "Eco-friendly Materials",
  "Recycled Materials",
  "Upcycled Materials",
  "Circular Materials",
  "Cradle-to-Cradle",
  "Life Cycle Assessment",
  "Environmental Impact Assessment",
  "Carbon Footprint",
  "Carbon Neutrality",
  "Carbon Negative",
  "Climate Positive",
  "Regenerative Design",
  "Biomimicry",
  "Biophilic Design",
  "Nature-based Solutions",
  "Ecosystem Services",
  "Natural Capital",
  "Ecological Economics",
  "Environmental Economics",
  "Resource Economics",
  "Energy Economics",
  "Water Economics",
  "Food Economics",
  "Agricultural Economics",
  "Rural Economics",
  "Urban Economics",
  "Regional Economics",
  "Spatial Economics",
  "Transportation Economics",
  "Health Economics",
  "Education Economics",
  "Labor Economics",
  "Public Economics",
  "Welfare Economics",
  "Development Economics",
  "Growth Economics",
  "Innovation Economics",
  "Knowledge Economics",
  "Information Economics",
  "Network Economics",
  "Platform Economics",
  "Digital Economics",
  "Data Economics",
  "Attention Economics",
  "Reputation Economics",
  "Trust Economics",
  "Social Capital",
  "Human Capital",
  "Intellectual Capital",
  "Cultural Capital",
  "Symbolic Capital",
  "Economic Capital",
  "Financial Capital",
  "Physical Capital",
  "Natural Capital",
  "Built Capital",
  "Infrastructure Capital",
  "Digital Capital",
  "Data Capital",
  "Algorithmic Capital",
  "Platform Capital",
  "Network Capital",
  "Social Network Analysis",
  "Network Science",
  "Complex Systems",
  "Systems Theory",
  "Cybernetics",
  "Information Theory",
  "Communication Theory",
  "Media Theory",
  "Cultural Theory",
  "Social Theory",
  "Political Theory",
  "Economic Theory",
  "Game Theory",
  "Decision Theory",
  "Rational Choice Theory",
  "Behavioral Economics",
  "Experimental Economics",
  "Neuroeconomics",
  "Psychoeconomics",
  "Sociological Economics",
  "Anthropological Economics",
  "Historical Economics",
  "Institutional Economics",
  "Evolutionary Economics",
  "Complexity Economics",
  "Heterodox Economics",
  "Post-Keynesian Economics",
  "Austrian Economics",
  "Marxist Economics",
  "Feminist Economics",
  "Ecological Economics",
  "Social Economics",
  "Solidarity Economics",
  "Community Economics",
  "Local Economics",
  "Regional Economics",
  "National Economics",
  "Global Economics",
  "International Economics",
  "World Economics",
  "Comparative Economics",
  "Cross-cultural Economics",
  "Interdisciplinary Economics",
  "Transdisciplinary Economics",
  "Multidisciplinary Economics",
  "Integrative Economics",
  "Holistic Economics",
  "Systems Economics",
  "Network Economics",
  "Platform Economics",
  "Digital Economics",
  "Data Economics",
  "Algorithmic Economics",
  "AI Economics",
  "Machine Learning Economics",
  "Deep Learning Economics",
  "Neural Network Economics",
  "Artificial Neural Networks",
  "Convolutional Neural Networks",
  "Recurrent Neural Networks",
  "Long Short-Term Memory",
  "Transformer Networks",
  "Attention Mechanisms",
  "Self-attention",
  "Multi-head Attention",
  "Cross-attention",
  "Graph Neural Networks",
  "Graph Attention Networks",
  "Graph Convolutional Networks",
  "Message Passing Neural Networks",
  "GraphSAGE",
  "Graph Isomorphism Networks",
  "Graph Neural Networks",
  "Geometric Deep Learning",
  "Topological Data Analysis",
  "Persistent Homology",
  "Morse Theory",
  "Differential Geometry",
  "Algebraic Geometry",
  "Arithmetic Geometry",
  "Algebraic Number Theory",
  "Analytic Number Theory",
  "Combinatorial Number Theory",
  "Computational Number Theory",
  "Algorithmic Number Theory",
  "Cryptographic Number Theory",
  "Elliptic Curve Cryptography",
  "Lattice-based Cryptography",
  "Post-quantum Cryptography",
  "Quantum Cryptography",
  "Quantum Key Distribution",
  "Quantum Random Number Generation",
  "Quantum Entanglement",
  "Quantum Superposition",
  "Quantum Interference",
  "Quantum Tunneling",
  "Quantum Teleportation",
  "Quantum Error Correction",
  "Quantum Error Mitigation",
  "Quantum Machine Learning",
  "Quantum Neural Networks",
  "Quantum Support Vector Machines",
  "Quantum Principal Component Analysis",
  "Quantum Fourier Transform",
  "Quantum Phase Estimation",
  "Quantum Amplitude Estimation",
  "Quantum Gradient Descent",
  "Quantum Optimization",
  "Quantum Annealing",
  "Adiabatic Quantum Computing",
  "Gate-based Quantum Computing",
  "Circuit-based Quantum Computing",
  "Measurement-based Quantum Computing",
  "Topological Quantum Computing",
  "Fault-tolerant Quantum Computing",
  "Noise-resistant Quantum Computing",
  "Error-corrected Quantum Computing",
  "Logical Quantum Computing",
  "Physical Quantum Computing",
  "Digital Quantum Computing",
  "Analog Quantum Computing",
  "Hybrid Quantum Computing",
  "Quantum-Classical Computing",
  "Quantum-inspired Computing",
  "Quantum-inspired Algorithms",
  "Quantum-inspired Optimization",
  "Quantum-inspired Machine Learning",
  "Quantum-inspired Neural Networks",
  "Quantum-inspired Support Vector Machines",
  "Quantum-inspired Principal Component Analysis",
  "Quantum-inspired Fourier Transform",
  "Quantum-inspired Phase Estimation",
  "Quantum-inspired Amplitude Estimation",
  "Quantum-inspired Gradient Descent",
  "Quantum-inspired Annealing",
  "Quantum-inspired Adiabatic Computing",
  "Quantum-inspired Gate-based Computing",
  "Quantum-inspired Circuit-based Computing",
  "Quantum-inspired Measurement-based Computing",
  "Quantum-inspired Topological Computing",
  "Quantum-inspired Fault-tolerant Computing",
  "Quantum-inspired Noise-resistant Computing",
  "Quantum-inspired Error-corrected Computing",
  "Quantum-inspired Logical Computing",
  "Quantum-inspired Physical Computing",
  "Quantum-inspired Digital Computing",
  "Quantum-inspired Analog Computing",
  "Quantum-inspired Hybrid Computing",
  "Quantum-inspired Quantum-Classical Computing",
  "Other",
];
