export const yearLevels = ["Freshman", "Sophomore", "Junior", "Senior"];

export const majors = [
  "Accounting",
  "Aerospace Engineering",
  "African American Studies",
  "Agriculture",
  "American Studies",
  "Animal Science",
  "Anthropology",
  "Applied Economics",
  "Applied Mathematics",
  "Architecture",
  "Art",
  "Art History",
  "Asian Studies",
  "Astronomy",
  "Atmospheric Science",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Biotechnology",
  "Business",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Classics",
  "Communications",
  "Comparative Literature",
  "Computer Science",
  "Criminal Justice",
  "Data Science",
  "Design",
  "Earth Sciences",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English",
  "Environmental Engineering",
  "Environmental Science",
  "European Studies",
  "Film Studies",
  "Finance",
  "Food Science",
  "Forensic Science",
  "French",
  "Gender Studies",
  "Geography",
  "Geology",
  "German",
  "Global Studies",
  "Government",
  "Graphic Design",
  "Health Sciences",
  "History",
  "Hospitality Management",
  "Human Development",
  "Human Resources",
  "Industrial Engineering",
  "Information Science",
  "Information Technology",
  "International Relations",
  "Italian",
  "Journalism",
  "Landscape Architecture",
  "Latin American Studies",
  "Law",
  "Linguistics",
  "Management",
  "Marketing",
  "Materials Science",
  "Mathematics",
  "Mechanical Engineering",
  "Media Studies",
  "Medicine",
  "Middle Eastern Studies",
  "Music",
  "Natural Resources",
  "Neuroscience",
  "Nursing",
  "Nutrition",
  "Operations Research",
  "Philosophy",
  "Physics",
  "Plant Science",
  "Political Science",
  "Psychology",
  "Public Health",
  "Public Policy",
  "Public Relations",
  "Religious Studies",
  "Russian",
  "Social Work",
  "Sociology",
  "Spanish",
  "Statistics",
  "Theater",
  "Urban Planning",
  "Veterinary Medicine",
  "Women's Studies",
  "Other",
];

// Centralize picker option sets used across the app
export const genders = ["Male", "Female", "Non-Binary"];

export const orientations = [
  "Heterosexual",
  "Homosexual",
  "Bisexual",
  "Pansexual",
];
