import { Profile } from "../types/App";

export const mockProfiles: Profile[] = [
  {
    firstName: "Sarah",
    age: 20,
    yearLevel: "Junior",
    major: "Computer Science",
    images: [""],
    aboutMe: "Coffee addict and coding enthusiast. Looking for study buddies!",
    q1: "Learn three new programming languages and build a startup",
    q2: "Code together, grab coffee, or debug each other's projects",
    q3: "Book: Clean Code, Movie: Social Network, Song: Mr. Brightside",
    q4: "I love solving puzzles and creating things from scratch",
    q5: "The quiet corner of the engineering building with huge windows",
    q6: "Photography, hiking, playing piano, and collecting vintage computers",
    email: "sarah.johnson@gmail.com",
  },
  {
    firstName: "Michael",
    age: 19,
    yearLevel: "Sophomore",
    major: "Biology",
    images: [""],
    aboutMe:
      "Pre-med student with a passion for research. Love playing basketball!",
    q1: "Get published in a research journal and maintain a 4.0 GPA",
    q2: "Study for MCAT, play basketball, or do lab work",
    q3: "Book: Gray's Anatomy, Movie: Patch Adams, Song: The Scientist",
    q4: "I want to understand how life works at the molecular level",
    q5: "The medical library's third floor by the anatomy section",
    q6: "Basketball, chess, cooking, and volunteering at the hospital",
    email: "michael.chen@gmail.com",
  },
  {
    firstName: "KJ",
    age: 19,
    yearLevel: "Junior",
    major: "Business",
    images: [""],
    aboutMe: "Just a chill guy looking to network and make connections",
    q1: "Launch my first startup and attend entrepreneurship conference",
    q2: "Brainstorm business ideas, workout, or grab lunch",
    q3: "Book: Zero to One, Movie: Wolf of Wall Street, Song: Can't Tell Me Nothing",
    q4: "I want to create valuable solutions for real-world problems",
    q5: "Business school cafe - best coffee and networking spot",
    q6: "Playing basketball, stock trading, and attending startup events",
    email: "kj.heinz@gmail.com",
  },
];
